/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/bms_state.h
  Source: /home/songguoqing/sim2real/idl/bms_state.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_BMS_STATE_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_BMS_STATE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__BmsState_
{
  uint16_t bms_state;
  uint16_t afe_state;
  uint32_t bms_alarms;
  uint16_t battery_level;
  uint16_t battery_health;
  uint16_t pcb_board_temp;
  uint16_t afe_chip_temp;
  uint16_t battery_now_current;
  uint16_t cells_voltage[16];
  uint16_t battery_pack_current_voltage;
  uint16_t battery_pack_io_voltage;
  uint32_t bms_work_time;
  uint16_t bms_hardware_version;
  uint16_t bms_software_version;
  uint16_t heartbeat;
} dobot_atom_msg_dds__BmsState_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__BmsState__desc;

#define dobot_atom_msg_dds__BmsState___alloc() \
((dobot_atom_msg_dds__BmsState_*) dds_alloc (sizeof (dobot_atom_msg_dds__BmsState_)));

#define dobot_atom_msg_dds__BmsState__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__BmsState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_BMS_STATE_H */
