/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/clear_errors.h
  Source: /home/songguoqing/sim2real/idl/clear_errors.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_CLEAR_ERRORS_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_CLEAR_ERRORS_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__ClearErrors_
{
  int32_t msg_id;
} dobot_atom_msg_dds__ClearErrors_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__ClearErrors__desc;

#define dobot_atom_msg_dds__ClearErrors___alloc() \
((dobot_atom_msg_dds__ClearErrors_*) dds_alloc (sizeof (dobot_atom_msg_dds__ClearErrors_)));

#define dobot_atom_msg_dds__ClearErrors__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__ClearErrors__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_CLEAR_ERRORS_H */
