/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/hands_state.h
  Source: /home/songguoqing/sim2real/idl/hands_state.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_HANDS_STATE_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_HANDS_STATE_H

#include "motor_state.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__HandsState_
{
  struct dobot_atom_msg_dds__MotorState_ hands[12];
} dobot_atom_msg_dds__HandsState_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__HandsState__desc;

#define dobot_atom_msg_dds__HandsState___alloc() \
((dobot_atom_msg_dds__HandsState_*) dds_alloc (sizeof (dobot_atom_msg_dds__HandsState_)));

#define dobot_atom_msg_dds__HandsState__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__HandsState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_HANDS_STATE_H */
