/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/hands_cmd.h
  Source: /home/songguoqing/sim2real/idl/hands_cmd.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_HANDS_CMD_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_HANDS_CMD_H

#include "motor_cmd.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__HandsCmd_
{
  struct dobot_atom_msg_dds__MotorCmd_ hands[12];
} dobot_atom_msg_dds__HandsCmd_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__HandsCmd__desc;

#define dobot_atom_msg_dds__HandsCmd___alloc() \
((dobot_atom_msg_dds__HandsCmd_*) dds_alloc (sizeof (dobot_atom_msg_dds__HandsCmd_)));

#define dobot_atom_msg_dds__HandsCmd__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__HandsCmd__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_HANDS_CMD_H */
