/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/imu_state.h
  Source: /home/songguoqing/sim2real/idl/imu_state.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_IMU_STATE_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_IMU_STATE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__IMUState_
{
  float quaternion[4];
  float gyroscope[3];
  float accelerometer[3];
  float rpy[3];
  uint8_t temperature;
} dobot_atom_msg_dds__IMUState_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__IMUState__desc;

#define dobot_atom_msg_dds__IMUState___alloc() \
((dobot_atom_msg_dds__IMUState_*) dds_alloc (sizeof (dobot_atom_msg_dds__IMUState_)));

#define dobot_atom_msg_dds__IMUState__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__IMUState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_IMU_STATE_H */
