/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/motor_state.h
  Source: /home/songguoqing/sim2real/idl/motor_state.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_MOTOR_STATE_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_MOTOR_STATE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__MotorState_
{
  uint8_t mode;
  float q;
  float dq;
  float ddq;
  float tau_est;
  float q_raw;
  float dq_raw;
  float ddq_raw;
  uint8_t mcu_temp;
  uint8_t mos_temp;
  uint8_t motor_temp;
  uint8_t bus_voltage;
} dobot_atom_msg_dds__MotorState_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__MotorState__desc;

#define dobot_atom_msg_dds__MotorState___alloc() \
((dobot_atom_msg_dds__MotorState_*) dds_alloc (sizeof (dobot_atom_msg_dds__MotorState_)));

#define dobot_atom_msg_dds__MotorState__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__MotorState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_MOTOR_STATE_H */
