/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/set_fsm_id.h
  Source: /home/songguoqing/sim2real/idl/set_fsm_id.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_SET_FSM_ID_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_SET_FSM_ID_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__SetFsmId_
{
  uint16_t id;
} dobot_atom_msg_dds__SetFsmId_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__SetFsmId__desc;

#define dobot_atom_msg_dds__SetFsmId___alloc() \
((dobot_atom_msg_dds__SetFsmId_*) dds_alloc (sizeof (dobot_atom_msg_dds__SetFsmId_)));

#define dobot_atom_msg_dds__SetFsmId__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__SetFsmId__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_SET_FSM_ID_H */
