/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/bms_cmd.h
  Source: /home/songguoqing/sim2real/idl/bms_cmd.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_BMS_CMD_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_BMS_CMD_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__BmsCmd_
{
  uint16_t clear_errors;
} dobot_atom_msg_dds__BmsCmd_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__BmsCmd__desc;

#define dobot_atom_msg_dds__BmsCmd___alloc() \
((dobot_atom_msg_dds__BmsCmd_*) dds_alloc (sizeof (dobot_atom_msg_dds__BmsCmd_)));

#define dobot_atom_msg_dds__BmsCmd__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__BmsCmd__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_BMS_CMD_H */
