/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/main_nodes_state.h
  Source: /home/songguoqing/sim2real/idl/main_nodes_state.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_MAIN_NODES_STATE_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_MAIN_NODES_STATE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__AxisStateInfo_
{
  uint8_t servo_state;
  uint16_t error_code;
  uint16_t warn_code;
  int32_t pos_err_code;
  int32_t vel_err_code;
  int32_t torque_err_code;
  uint8_t node_state;
  uint8_t display_op_mode;
  bool is_virtual;
  uint8_t mcu_temp;
  uint8_t mos_temp;
  uint8_t motor_temp;
  uint8_t bus_voltage;
  uint16_t software_version;
} dobot_atom_msg_dds__AxisStateInfo_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__AxisStateInfo__desc;

#define dobot_atom_msg_dds__AxisStateInfo___alloc() \
((dobot_atom_msg_dds__AxisStateInfo_*) dds_alloc (sizeof (dobot_atom_msg_dds__AxisStateInfo_)));

#define dobot_atom_msg_dds__AxisStateInfo__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__AxisStateInfo__desc, (o))

typedef struct dobot_atom_msg_dds__EcatSlaveInfo_
{
  bool is_virtual;
  uint8_t slave_state;
  uint16_t error_code;
  uint16_t software_version;
} dobot_atom_msg_dds__EcatSlaveInfo_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__EcatSlaveInfo__desc;

#define dobot_atom_msg_dds__EcatSlaveInfo___alloc() \
((dobot_atom_msg_dds__EcatSlaveInfo_*) dds_alloc (sizeof (dobot_atom_msg_dds__EcatSlaveInfo_)));

#define dobot_atom_msg_dds__EcatSlaveInfo__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__EcatSlaveInfo__desc, (o))

typedef struct dobot_atom_msg_dds__MainNodesState_
{
  struct dobot_atom_msg_dds__AxisStateInfo_ left_leg[6];
  struct dobot_atom_msg_dds__AxisStateInfo_ right_leg[6];
  struct dobot_atom_msg_dds__AxisStateInfo_ waist;
  struct dobot_atom_msg_dds__AxisStateInfo_ left_arm[7];
  struct dobot_atom_msg_dds__AxisStateInfo_ right_arm[7];
  struct dobot_atom_msg_dds__AxisStateInfo_ head[2];
  struct dobot_atom_msg_dds__EcatSlaveInfo_ ecat2can[2];
} dobot_atom_msg_dds__MainNodesState_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__MainNodesState__desc;

#define dobot_atom_msg_dds__MainNodesState___alloc() \
((dobot_atom_msg_dds__MainNodesState_*) dds_alloc (sizeof (dobot_atom_msg_dds__MainNodesState_)));

#define dobot_atom_msg_dds__MainNodesState__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__MainNodesState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_MAIN_NODES_STATE_H */
