/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/upper_state.h
  Source: /home/songguoqing/sim2real/idl/upper_state.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_UPPER_STATE_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_UPPER_STATE_H

#include "imu_state.h"

#include "motor_state.h"

#include "bms_state.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__UpperState_
{
  char robot_type[16];
  bool is_upper_control;
  uint16_t fsm_id;
  struct dobot_atom_msg_dds__MotorState_ motor_state[17];
  struct dobot_atom_msg_dds__BmsState_ bms_state;
  uint8_t wireless_remote[40];
  uint32_t reserve;
} dobot_atom_msg_dds__UpperState_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__UpperState__desc;

#define dobot_atom_msg_dds__UpperState___alloc() \
((dobot_atom_msg_dds__UpperState_*) dds_alloc (sizeof (dobot_atom_msg_dds__UpperState_)));

#define dobot_atom_msg_dds__UpperState__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__UpperState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_UPPER_STATE_H */
