/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/upper_cmd.h
  Source: /home/songguoqing/sim2real/idl/upper_cmd.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_UPPER_CMD_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_UPPER_CMD_H

#include "motor_cmd.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__UpperCmd_
{
  struct dobot_atom_msg_dds__MotorCmd_ motor_cmd[17];
} dobot_atom_msg_dds__UpperCmd_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__UpperCmd__desc;

#define dobot_atom_msg_dds__UpperCmd___alloc() \
((dobot_atom_msg_dds__UpperCmd_*) dds_alloc (sizeof (dobot_atom_msg_dds__UpperCmd_)));

#define dobot_atom_msg_dds__UpperCmd__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__UpperCmd__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_UPPER_CMD_H */
